### ISSUE TITLE
Indy Dataset

### ISSUE THREAD

**Issue by alfredgu001324** [linklab-uva/deep-dynamics#10]
Thanks for the great work, it is really interesting! I am wondering where does the Indy dataset come from (the csv files). I assume they are from the RACECAR dataset? Do you mind sharing which scenarios do they correspond to (SOLO-FAST-100-140, SOLO-FAST-140 etc.) and how do you process them specifically? do you have any data extraction script?

Looking forward to your reply!

**Comment by john-chrosniak** [comment]
Thanks for reaching out, and apologies for the delayed response! The script I used to convert a ROS 2 bag to csv format is located [here](https://github.com/linklab-uva/deep-dynamics/blob/main/deep_dynamics/tools/rosbag_data_convert.py).

The data I used is not a part of the RACECAR dataset, it is newer data that our team collected after the release of RACECAR.

**Comment by alfredgu001324** [comment]
Thanks for the quick reply! I am wondering if this conversion can also be done for the nuscenes format (as I only downloaded this format lol)? I am not sure if the acc/steering/throttle information are available in the nuscenes format. 

Also, would the RACECAR contain more datapoints than this version of datasets?

**Comment by john-chrosniak** [comment]
Both the nuScenes and ROS 2 bag formats of RACECAR do not have steering and throttle information, so unfortunately the dataset cannot be used here

**Comment by alfredgu001324** [comment]
Oh I see, thanks for the clarifications and your help! Have a good rest of the day!
