### ISSUE TITLE
no license

### ISSUE THREAD

**Issue by Wang4758** [linklab-uva/deep-dynamics#6]
Hi @john-chrosniak,

Thank you for open sourcing the code for your paper. I see that there is no license for the project. Could you please create a license? By default, no license means no one may reproduce, distribute, or create derivative works from your work, see https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository.

Thank you very much in advance.

**Comment by john-chrosniak** [comment]
Glad you're interested in using my work! I just added a license so I closed the issue.
