### ISSUE TITLE
Output estimated tire parameters

### ISSUE THREAD

**Issue by alexbuyval** [linklab-uva/deep-dynamics#9]
Hi,

Thank you for excellent work! 

There is "TABLE III COMPARISON OF ESTIMATED MODEL COEFFICIENTS" in the paper. I wonder is there any script in the code to output these coefficients from the trained model?

**Comment by john-chrosniak** [comment]
Hi, thanks for your interest in Deep Dynamics! You can output the average coefficient estimates for the trained model using the script `model/evaulate.py` with the `--eval_coeffs` argument.

**Comment by alexbuyval** [comment]
Thank you!
It is exactly what I needed.
